FROM ubuntu:18.04

LABEL maintainer="Muhammed Ugur <meugur@umich.edu>"

ARG TF_WHL_PACKAGE=tensorflow-2.4.1-cp36-cp36m-linux_x86_64.whl
ARG TF_WHL_DIR

SHELL ["/bin/bash", "-c"]

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y \
      git \
      build-essential \
      software-properties-common \
      ca-certificates \
      wget \
      curl \
      python3-pip
RUN apt clean

RUN pip3 install --upgrade pip

COPY $TF_WHL_DIR/$TF_WHL_PACKAGE /root/

RUN pip install /root/$TF_WHL_PACKAGE
RUN pip install \
    opencv-python-headless \
    pycocotools

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN cd /root && git clone --recursive https://github.com/mlcommons/inference && \
    cd /root/inference/loadgen && \
    CFLAGS="-std=c++14" python setup.py install

ADD ["datasets/", "/root/datasets/"]
ADD ["models/", "/root/models/"]

RUN python \
    /root/inference/vision/classification_and_detection/tools/ssd-nhwc.py \
    /root/models/resnet34_tf.22.1.pb && \
    mv /root/models/resnet34_tf.22.1.pb.patch /root/models/resnet34_tf.22.1.pb

WORKDIR /root/inference/vision/classification_and_detection
