FROM ubuntu:18.04

LABEL maintainer="Muhammed Ugur <meugur@umich.edu>"

SHELL ["/bin/bash", "-c"]

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y \
      git \
      build-essential \
      software-properties-common \
      ca-certificates \
      wget \
      curl
RUN apt clean
