FROM ubuntu:20.04

LABEL maintainer="Muhammed Ugur <meugur@umich.edu>"

SHELL ["/bin/bash", "-c"]

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y \
      git \
      build-essential \
      software-properties-common \
      ca-certificates \
      wget \
      curl \
      python3-pip \
      linux-tools-generic
# RUN add-apt-repository ppa:deadsnakes/ppa && \
#     apt-get update && \
#     apt-get install -y python3.6
RUN apt clean

RUN rm /usr/bin/perf && ln -s /usr/lib/linux-tools-5.4.0-70/perf /usr/bin/perf

RUN pip3 install --upgrade pip

RUN pip install \
    opencv-python-headless \
    pycocotools \
    tensorflow
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN cd /root && git clone --recursive https://github.com/mlcommons/inference && \
    cd /root/inference/loadgen && \
    CFLAGS="-std=c++14" python setup.py install

ADD ["models/", "/root/models/"]
RUN python \
    /root/inference/vision/classification_and_detection/tools/ssd-nhwc.py \
    /root/models/resnet34_tf.22.1.pb && \
    mv /root/models/resnet34_tf.22.1.pb.patch /root/models/resnet34_tf.22.1.pb
ADD ["datasets/", "/root/datasets/"]
ADD ["data/", "/root/data/"]

WORKDIR /root/inference/vision/classification_and_detection
