FROM ubuntu:18.04

LABEL maintainer="Muhammed Ugur <meugur@umich.edu>"

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y \
    clang \
    git \
    python3-pip \
    build-essential \
    software-properties-common \
    cmake \
    wget \
    curl
RUN apt clean

RUN pip3 install --upgrade pip

ADD ["pt/pytorch/", "/root/pytorch/"]

RUN cd /root/pytorch && pip install -r requirements.txt

WORKDIR /root/pytorch
